In [1]:

from TableDataClass import TableData
import pandas as pd
import glob


main=[]
for pdf in glob.glob('./PDFS/*'):
    extractor=TableData(pdf)
    temp=extractor.extractData()
    temp['File']=pdf.replace('./PDFS/',"")
    main.append(temp)

df=pd.concat(main,ignore_index=True)  
df

,Order No.,OrderTime,TradeNo.,TradeTime,Company Name,Buy(B) /Sell(S),Quantity,Gross Rate/trade price per Unit(Rs),Brokerage perUnit,NetRate perUnit(Rs),NetTotal(BeforeLevies)(Rs.),Contract No,TradeDate,Trading,UCC,Name,ISIN,File
0,1000000014637162,13:26:59,05370942,15:15:54,APOLLO PIPES LIMITED.,B,10,978.40,1.9570,980.36,9803.57,212206974642,20-jul-2021,2070426,2070426,KULDEEP SETHIA,INE126J01016,ContractNote (8).pdf
1,1000000014637162,13:26:59,05603752,15:25:37,APOLLO PIPES LIMITED.,B,40,978.40,1.9568,980.36,39214.27,212206974642,20-jul-2021,2070426,2070426,KULDEEP SETHIA,INE126J01016,ContractNote (8).pdf
2,1000000014637162,13:26:59,05630863,15:27:03,APOLLO PIPES LIMITED.,B,3,978.40,1.9567,980.36,2941.07,212206974642,20-jul-2021,2070426,2070426,KULDEEP SETHIA,INE126J01016,ContractNote (8).pdf
3,1000000014651093,13:27:21,03983623,13:27:24,BHARTI AIRTEL LIMITED.,B,100,526.10,1.0522,527.15,52715.22,212206974642,20-jul-2021,2070426,2070426,KULDEEP SETHIA,INE397D01024,ContractNote (8).pdf
4,1000000014664400,13:27:43,03986037,13:27:43,CAN FIN HOMES LTD.,B,16,527.05,1.0544,528.10,8449.67,212206974642,20-jul-2021,2070426,2070426,KULDEEP SETHIA,INE477A01020,ContractNote (8).pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,1100000015836542,13:37:29,29502165,13:37:29,DCB BANK LIMITED.,S,195,86.55,0.1731,86.38,16843.50,222300397280,07-apr-2022,2070426,2070426,KULDEEP SETHIA,INE503A01015,ContractNote (30).pdf
297,1100000015836542,13:37:29,29502166,13:37:29,DCB BANK LIMITED.,S,924,86.55,0.1731,86.38,79812.26,222300397280,07-apr-2022,2070426,2070426,KULDEEP SETHIA,INE503A01015,ContractNote (30).pdf
298,1100000015836542,13:37:29,29502167,13:37:29,DCB BANK LIMITED.,S,1,86.55,0.1700,86.38,86.38,222300397280,07-apr-2022,2070426,2070426,KULDEEP SETHIA,INE503A01015,ContractNote (30).pdf
299,1100000015836542,13:37:29,29502168,13:37:29,DCB BANK LIMITED.,S,3276,86.55,0.1731,86.38,282970.72,222300397280,07-apr-2022,2070426,2070426,KULDEEP SETHIA,INE503A01015,ContractNote (30).pdf
300,1100000015836542,13:37:29,29502169,13:37:29,DCB BANK LIMITED.,S,8,86.55,0.1725,86.38,691.02,222300397280,07-apr-2022,2070426,2070426,KULDEEP SETHIA,INE503A01015,ContractNote (30).pdf